config/routes.rb
Rails.application.routes.draw do

  resources :purchases, except: [:show, :edit, :update]
  resources :lemonade_types, except: [:show]

  root 'purchases#index'

end

app/models/lemonade_type.rb
class LemonadeType < ActiveRecord::Base

  validates :label, :price, presence: true

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

  belongs_to :lemonade_type

  validates :quantity, :lemonade_type_id, presence: true

  def sale_total
    lemonade_type.price * quantity
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lemonade_types_controller.rb
class LemonadeTypesController < ApplicationController

  before_action :load_lemonade_type, except: [:index, :create, :new]

  def index
    @lemonade_types = LemonadeType.all
  end

  def new
  end

  def create
    @lemonade_type = LemonadeType.new(lemonade_type_params)
    if @lemonade_type.save
      redirect_to lemonade_types_path, notice: 'Lemonade type created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lemonade_type.update(lemonade_type_params)
      redirect_to lemonade_types_path, notice: 'Lemonade type updated.'
    else
      render :edit
    end
  end

  def destroy
    purchases_using_this_type = Purchase.where(lemonade_type: @lemonade_type)
    if purchases_using_this_type.count > 0
      redirect_to lemonade_types_path, alert: "You can't delete a lemonade type that has been purchased."
    else
      @lemonade_type.destroy
      redirect_to lemonade_types_path, notice: "Lemonade type deleted."
    end
  end

  private

  def load_lemonade_type
    @lemonade_type = LemonadeType.find(params[:id])
  end

  def lemonade_type_params
    params.require(:lemonade_type).permit(:label, :price, :color)
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_action :load_purchase, only: [:destroy]

  def index
    @purchases = Purchase.all.order('created_at DESC')
  end

  def new
  end

  def create
    @purchase = Purchase.new(purchases_params)
    if @purchase.save
      redirect_to purchases_path, notice: 'Purchase recorded!'
    else
      render :new
    end
  end

  def destroy
    @purchase.destroy
    redirect_to purchases_path, notice: 'Purchase deleted'
  end

  private

  def load_purchase
    @purchase = Purchase.find(params[:id])
  end

  def purchases_params
    params.require(:purchase).permit(:quantity, :lemonade_type_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lemonade_types_helper.rb
module LemonadeTypesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KarlasLemonadeStand</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <h1>Karla's Lemonade Stand</h1>
  <% flash.each do |name, msg| -%>
    <% alert_type = (name == 'notice' ? 'success' : 'danger') %>
    <div class="alert alert-<%= alert_type %>">
      <%= msg %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/lemonade_types/edit.html.erb
<h2>Edit lemonade type</h2>

<h3><%= @lemonade_type.label %></h3>

<% @lemonade_type.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

<%= form_for :lemonade_type, url: lemonade_type_path(@lemonade_type), method: :put do |f| %>
  <p>
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </p>
 
  <p>
    <%= f.label :color %><br>
    <%= f.select :color, ['yellow', 'pink', 'orange'] %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lemonade_types/index.html.erb
<h2>Lemonade Types</h2>
<p><a href='<%= purchases_path %>'>&larr; Back to purchases</a> | <a href='<%= new_lemonade_type_path %>'>New lemonade type</a></p>

<table class="table">
  <thead>
    <th>Label</th>
    <th>Price</th>
    <th>Color</th>
    <th></th>
  </thead>
  <tbody>
    <% @lemonade_types.each do |lemonade_type| %>
      <tr>
        <td><%= lemonade_type.label %></td>
        <td><%= number_to_currency(lemonade_type.price) %></td>
        <td><%= lemonade_type.color %></td>
        <td><%= link_to 'Edit', edit_lemonade_type_path(lemonade_type) %> | <%= link_to 'Delete', lemonade_type_path(lemonade_type), method: :delete, data: { confirm: "Are you sure you want to delete this lemonade type?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lemonade_types/new.html.erb
<h2>New lemonade type</h2>

<% if @lemonade_type %>
  <% @lemonade_type.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

<%= form_for :lemonade_type, url: lemonade_types_path do |f| %>
  <p>
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </p>
 
  <p>
    <%= f.label :color %><br>
    <%= f.select :color, ['yellow', 'pink', 'orange'] %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/purchases/index.html.erb
<p><%= link_to 'Record purchase', new_purchase_path %> | <%= link_to 'Lemonade types', lemonade_types_path %></p>

<table class="table table-striped">
  <thead>
    <th>Purchase ID</th>
    <th>Purchase date/time</th>
    <th>Lemonade Type</th>
    <th>Quantity</th>
    <th>Sale total</th>
    <th></th>
  </thead>
  <tbody>
    <% total = 0 %>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.id %></td>
        <td><%= purchase.created_at.to_formatted_s(:short) %></td>
        <td><%= purchase.lemonade_type.label %></td>
        <td><%= purchase.quantity %></td>
        <td><%= number_to_currency(purchase.sale_total) %></td>
        <td><%= link_to 'Delete', purchase_path(purchase), method: :delete, data: { confirm: "Are you sure you want to delete this purchase?" } %></td>
      </tr>
      <% total += purchase.sale_total %>
    <% end %>
    <tr>
      <td colspan="4">
        <strong>
          Total sales
        </strong>
      </td>
      <td>
        <strong>
          <%= number_to_currency(total) %>
        </strong>
      </td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/purchases/new.html.erb
<h2>Record purchase</h2>

<% if @purchase %>
  <% @purchase.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

<%= form_for :purchase, url: purchases_path do |f| %>
  <p>
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </p>
 
  <p>
    <%= f.label :lemonade_type_id, 'Lemonade Type' %><br>
    <%= f.select :lemonade_type_id, options_from_collection_for_select(LemonadeType.all, :id, :label) %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>